import type { DdfProperty } from "./types";

// ---------------------------------------------------------------
// MOCK DATA — placeholder for the live CREA DDF feed.
// Shaped like real RESO Property responses so the UI needs no
// changes when DDF_USE_LIVE=true and real credentials are set.
// Photos are placeholder images from picsum.photos.
// ---------------------------------------------------------------

function media(seed: string, count: number) {
  // Stable numeric "lock" per seed so each listing keeps the same photos
  let hash = 0;
  for (const ch of seed) hash = (hash * 31 + ch.charCodeAt(0)) % 9973;
  return Array.from({ length: count }, (_, i) => ({
    MediaKey: `${seed}-m${i + 1}`,
    MediaURL: `https://loremflickr.com/1200/800/house,home?lock=${hash + i}`,
    Order: i + 1,
  }));
}

export const MOCK_LISTINGS: DdfProperty[] = [
  {
    ListingKey: "ubk-0001",
    ListingId: "X9501234",
    StandardStatus: "Active",
    UnparsedAddress: "245 Bank Street Unit 1204",
    City: "Ottawa",
    StateOrProvince: "ON",
    PostalCode: "K2P 1X4",
    SubdivisionName: "Centretown",
    Latitude: 45.4146,
    Longitude: -75.6946,
    ListPrice: 489900,
    PropertyType: "Residential",
    PropertySubType: "Condo Apartment",
    BedroomsTotal: 2,
    BathroomsTotalInteger: 2,
    LivingArea: 920,
    YearBuilt: 2016,
    PublicRemarks:
      "Bright corner unit in the heart of Centretown with floor-to-ceiling windows, an open-concept kitchen with quartz counters, and a wraparound balcony overlooking Bank Street. Steps to restaurants, the canal, and transit.",
    ListOfficeName: "Capital Edge Realty Ltd., Brokerage",
    ModificationTimestamp: "2026-06-09T14:22:00Z",
    ListingContractDate: "2026-05-28",
    Media: media("centretown-condo", 5),
  },
  {
    ListingKey: "ubk-0002",
    ListingId: "X9501871",
    StandardStatus: "Active",
    UnparsedAddress: "78 Glebe Avenue",
    City: "Ottawa",
    StateOrProvince: "ON",
    PostalCode: "K1S 2C3",
    SubdivisionName: "The Glebe",
    Latitude: 45.4034,
    Longitude: -75.6902,
    ListPrice: 1249000,
    PropertyType: "Residential",
    PropertySubType: "Single Family Residence",
    BedroomsTotal: 4,
    BathroomsTotalInteger: 3,
    LivingArea: 2450,
    LotSizeArea: 0.11,
    YearBuilt: 1924,
    PublicRemarks:
      "Classic Glebe red-brick home blending character and modern updates: original trim and hardwood, a renovated chef's kitchen, finished basement, and a landscaped backyard. Walk to Lansdowne and the canal.",
    ListOfficeName: "Riverview Homes Realty, Brokerage",
    ModificationTimestamp: "2026-06-10T09:05:00Z",
    ListingContractDate: "2026-06-02",
    Media: media("glebe-brick", 6),
  },
  {
    ListingKey: "ubk-0003",
    ListingId: "X9502244",
    StandardStatus: "Active",
    UnparsedAddress: "112 Maple Grove Road",
    City: "Kanata",
    StateOrProvince: "ON",
    PostalCode: "K2V 0B9",
    SubdivisionName: "Kanata Lakes",
    Latitude: 45.3088,
    Longitude: -75.9101,
    ListPrice: 879900,
    PropertyType: "Residential",
    PropertySubType: "Single Family Residence",
    BedroomsTotal: 4,
    BathroomsTotalInteger: 4,
    LivingArea: 2780,
    LotSizeArea: 0.14,
    YearBuilt: 2008,
    PublicRemarks:
      "Executive family home in Kanata Lakes backing onto green space. Hardwood main level, granite kitchen with island, four generous bedrooms, and a fully finished walkout basement with rec room and wet bar.",
    ListOfficeName: "Northgate Realty Group, Brokerage",
    ModificationTimestamp: "2026-06-08T17:40:00Z",
    ListingContractDate: "2026-05-21",
    Media: media("kanata-lakes", 5),
  },
  {
    ListingKey: "ubk-0004",
    ListingId: "X9502419",
    StandardStatus: "Active",
    UnparsedAddress: "59 Hartsmere Drive",
    City: "Stittsville",
    StateOrProvince: "ON",
    PostalCode: "K2S 1Y6",
    Latitude: 45.2604,
    Longitude: -75.9264,
    ListPrice: 724900,
    PropertyType: "Residential",
    PropertySubType: "Townhouse",
    BedroomsTotal: 3,
    BathroomsTotalInteger: 3,
    LivingArea: 1850,
    YearBuilt: 2019,
    PublicRemarks:
      "Nearly-new executive townhome in Stittsville with an open main floor, upgraded kitchen with breakfast bar, primary suite with walk-in closet and ensuite, and a fenced yard. Close to Trans-Canada Trail and top schools.",
    ListOfficeName: "Capital Edge Realty Ltd., Brokerage",
    ModificationTimestamp: "2026-06-10T11:18:00Z",
    ListingContractDate: "2026-06-05",
    Media: media("stittsville-town", 4),
  },
  {
    ListingKey: "ubk-0005",
    ListingId: "X9502580",
    StandardStatus: "Active",
    UnparsedAddress: "421 Longfields Drive",
    City: "Ottawa",
    StateOrProvince: "ON",
    PostalCode: "K2J 4T1",
    SubdivisionName: "Barrhaven",
    Latitude: 45.2752,
    Longitude: -75.7416,
    ListPrice: 814900,
    PropertyType: "Residential",
    PropertySubType: "Single Family Residence",
    BedroomsTotal: 4,
    BathroomsTotalInteger: 3,
    LivingArea: 2520,
    LotSizeArea: 0.1,
    YearBuilt: 2012,
    PublicRemarks:
      "Spacious Barrhaven single on a quiet stretch of Longfields: formal living and dining, eat-in kitchen overlooking the family room with gas fireplace, and a second-floor laundry. Minutes to Marketplace and transit.",
    ListOfficeName: "Southbridge Realty Inc., Brokerage",
    ModificationTimestamp: "2026-06-07T20:55:00Z",
    ListingContractDate: "2026-05-30",
    Media: media("barrhaven-single", 5),
  },
  {
    ListingKey: "ubk-0006",
    ListingId: "X9502733",
    StandardStatus: "Active",
    UnparsedAddress: "1480 Merivale Road Unit 308",
    City: "Nepean",
    StateOrProvince: "ON",
    PostalCode: "K2E 5P3",
    Latitude: 45.3473,
    Longitude: -75.7361,
    ListPrice: 389900,
    PropertyType: "Residential",
    PropertySubType: "Condo Apartment",
    BedroomsTotal: 1,
    BathroomsTotalInteger: 1,
    LivingArea: 680,
    YearBuilt: 2021,
    PublicRemarks:
      "Modern one-bedroom in Nepean with in-unit laundry, stainless appliances, a private balcony, underground parking, and a storage locker. Ideal first home or investment near Merivale's shops and services.",
    ListOfficeName: "Northgate Realty Group, Brokerage",
    ModificationTimestamp: "2026-06-09T08:30:00Z",
    ListingContractDate: "2026-06-01",
    Media: media("nepean-condo", 4),
  },
  {
    ListingKey: "ubk-0007",
    ListingId: "X9502901",
    StandardStatus: "Active",
    UnparsedAddress: "2034 Portobello Boulevard",
    City: "Orleans",
    StateOrProvince: "ON",
    PostalCode: "K4A 4V7",
    SubdivisionName: "Avalon",
    Latitude: 45.4731,
    Longitude: -75.4836,
    ListPrice: 689900,
    PropertyType: "Residential",
    PropertySubType: "Single Family Residence",
    BedroomsTotal: 3,
    BathroomsTotalInteger: 3,
    LivingArea: 2100,
    LotSizeArea: 0.09,
    YearBuilt: 2015,
    PublicRemarks:
      "Sun-filled Avalon home with a dramatic two-storey foyer, maple kitchen with pantry, cozy gas fireplace, and a primary retreat with five-piece ensuite. Walk to parks, ponds, and Aquaview trails in Orleans.",
    ListOfficeName: "Riverview Homes Realty, Brokerage",
    ModificationTimestamp: "2026-06-10T15:47:00Z",
    ListingContractDate: "2026-06-06",
    Media: media("orleans-avalon", 5),
  },
  {
    ListingKey: "ubk-0008",
    ListingId: "X9503058",
    StandardStatus: "Active",
    UnparsedAddress: "655 Cyrville Road",
    City: "Gloucester",
    StateOrProvince: "ON",
    PostalCode: "K1J 7S6",
    Latitude: 45.4262,
    Longitude: -75.6149,
    ListPrice: 549900,
    PropertyType: "Residential",
    PropertySubType: "Semi-Detached",
    BedroomsTotal: 3,
    BathroomsTotalInteger: 2,
    LivingArea: 1480,
    YearBuilt: 1987,
    PublicRemarks:
      "Well-kept semi in Gloucester with an updated kitchen and bath, newer windows, a finished lower level, and a deep fenced yard. Quick access to the LRT, Highway 417, and St. Laurent shopping.",
    ListOfficeName: "Southbridge Realty Inc., Brokerage",
    ModificationTimestamp: "2026-06-06T13:12:00Z",
    ListingContractDate: "2026-05-25",
    Media: media("gloucester-semi", 4),
  },
  {
    ListingKey: "ubk-0009",
    ListingId: "X9503187",
    StandardStatus: "Active",
    UnparsedAddress: "5520 Long Island Road",
    City: "Manotick",
    StateOrProvince: "ON",
    PostalCode: "K4M 1E9",
    Latitude: 45.2266,
    Longitude: -75.6837,
    ListPrice: 1589000,
    PropertyType: "Residential",
    PropertySubType: "Single Family Residence",
    BedroomsTotal: 5,
    BathroomsTotalInteger: 4,
    LivingArea: 3650,
    LotSizeArea: 0.46,
    YearBuilt: 2003,
    PublicRemarks:
      "Stately Manotick residence on a treed half-acre near the Rideau River: grand principal rooms, a chef's kitchen with butler's pantry, main-floor office, and a three-car garage. Village charm minutes from the city.",
    ListOfficeName: "Heritage River Realty, Brokerage",
    ModificationTimestamp: "2026-06-09T19:02:00Z",
    ListingContractDate: "2026-05-18",
    Media: media("manotick-estate", 6),
  },
  {
    ListingKey: "ubk-0010",
    ListingId: "X9503340",
    StandardStatus: "Active",
    UnparsedAddress: "7212 Parkway Road",
    City: "Greely",
    StateOrProvince: "ON",
    PostalCode: "K4P 1G6",
    Latitude: 45.2614,
    Longitude: -75.5594,
    ListPrice: 1099000,
    PropertyType: "Residential",
    PropertySubType: "Single Family Residence",
    BedroomsTotal: 4,
    BathroomsTotalInteger: 3,
    LivingArea: 3100,
    LotSizeArea: 0.73,
    YearBuilt: 2010,
    PublicRemarks:
      "Custom bungalow with loft on a private 0.7-acre lot in Greely. Vaulted great room with stone fireplace, oversized triple garage, screened porch, and a finished basement with gym and theatre space.",
    ListOfficeName: "Heritage River Realty, Brokerage",
    ModificationTimestamp: "2026-06-08T10:25:00Z",
    ListingContractDate: "2026-05-27",
    Media: media("greely-bungalow", 5),
  },
  {
    ListingKey: "ubk-0011",
    ListingId: "X9503495",
    StandardStatus: "Active",
    UnparsedAddress: "318 Kelly Farm Drive",
    City: "Ottawa",
    StateOrProvince: "ON",
    PostalCode: "K1T 0K3",
    SubdivisionName: "Findlay Creek",
    Latitude: 45.3097,
    Longitude: -75.6098,
    ListPrice: 759900,
    PropertyType: "Residential",
    PropertySubType: "Single Family Residence",
    BedroomsTotal: 4,
    BathroomsTotalInteger: 3,
    LivingArea: 2300,
    LotSizeArea: 0.08,
    YearBuilt: 2017,
    PublicRemarks:
      "Move-in-ready Findlay Creek home with 9-foot ceilings, upgraded laminate, a sunny kitchen with quartz island, and four bedrooms up. Steps to the boardwalk, parks, and the new shopping district.",
    ListOfficeName: "Capital Edge Realty Ltd., Brokerage",
    ModificationTimestamp: "2026-06-10T07:58:00Z",
    ListingContractDate: "2026-06-04",
    Media: media("findlay-creek", 5),
  },
  {
    ListingKey: "ubk-0012",
    ListingId: "X9503612",
    StandardStatus: "Active",
    UnparsedAddress: "950 Canadian Shield Avenue",
    City: "Ottawa",
    StateOrProvince: "ON",
    PostalCode: "K1V 2P4",
    SubdivisionName: "Riverside South",
    Latitude: 45.2829,
    Longitude: -75.6708,
    ListPrice: 699900,
    PropertyType: "Residential",
    PropertySubType: "Townhouse",
    BedroomsTotal: 3,
    BathroomsTotalInteger: 3,
    LivingArea: 1950,
    YearBuilt: 2022,
    PublicRemarks:
      "Contemporary end-unit townhome in Riverside South: open-concept main floor with chevron-pattern flooring, designer kitchen, loft-style second-floor family room, and a balcony off the primary suite. Near the new LRT extension.",
    ListOfficeName: "Southbridge Realty Inc., Brokerage",
    ModificationTimestamp: "2026-06-09T16:33:00Z",
    ListingContractDate: "2026-06-03",
    Media: media("riverside-south", 4),
  },
  {
    ListingKey: "ubk-0013",
    ListingId: "X9503777",
    StandardStatus: "Active",
    UnparsedAddress: "2845 Chamberland Street",
    City: "Rockland",
    StateOrProvince: "ON",
    PostalCode: "K4K 1L5",
    Latitude: 45.5453,
    Longitude: -75.2911,
    ListPrice: 569900,
    PropertyType: "Residential",
    PropertySubType: "Single Family Residence",
    BedroomsTotal: 3,
    BathroomsTotalInteger: 2,
    LivingArea: 1720,
    LotSizeArea: 0.13,
    YearBuilt: 2005,
    PublicRemarks:
      "Affordable family home in Rockland with a bright eat-in kitchen, three good-sized bedrooms, a finished basement with gas stove, and an above-ground pool in the fenced yard. Easy commute on the 174.",
    ListOfficeName: "Riverview Homes Realty, Brokerage",
    ModificationTimestamp: "2026-06-07T12:44:00Z",
    ListingContractDate: "2026-05-29",
    Media: media("rockland-family", 4),
  },
  {
    ListingKey: "ubk-0014",
    ListingId: "X9503918",
    StandardStatus: "Active",
    UnparsedAddress: "117 Falldown Lane",
    City: "Carp",
    StateOrProvince: "ON",
    PostalCode: "K0A 1L0",
    Latitude: 45.3502,
    Longitude: -76.0418,
    ListPrice: 939900,
    PropertyType: "Residential",
    PropertySubType: "Single Family Residence",
    BedroomsTotal: 4,
    BathroomsTotalInteger: 3,
    LivingArea: 2650,
    LotSizeArea: 0.31,
    YearBuilt: 2014,
    PublicRemarks:
      "Village-edge home in Carp on a premium pie lot: hardwood throughout the main, oversized windows, a mudroom off the double garage, and a covered rear porch with sunset views over the Carp Ridge.",
    ListOfficeName: "Northgate Realty Group, Brokerage",
    ModificationTimestamp: "2026-06-08T21:09:00Z",
    ListingContractDate: "2026-05-23",
    Media: media("carp-village", 5),
  },
  {
    ListingKey: "ubk-0015",
    ListingId: "X9504071",
    StandardStatus: "Active",
    UnparsedAddress: "36 Beaverbrook Lane",
    City: "Kanata",
    StateOrProvince: "ON",
    PostalCode: "K2K 1L3",
    SubdivisionName: "Beaverbrook",
    Latitude: 45.3216,
    Longitude: -75.8988,
    ListPrice: 524900,
    PropertyType: "Residential",
    PropertySubType: "Townhouse",
    BedroomsTotal: 3,
    BathroomsTotalInteger: 2,
    LivingArea: 1540,
    YearBuilt: 1976,
    PublicRemarks:
      "Updated Beaverbrook townhome surrounded by mature trees and walking paths. Refinished hardwood, renovated kitchen with subway tile, and a private patio backing onto greenbelt. Walk to Kanata's tech park.",
    ListOfficeName: "Capital Edge Realty Ltd., Brokerage",
    ModificationTimestamp: "2026-06-10T13:20:00Z",
    ListingContractDate: "2026-06-07",
    Media: media("kanata-beaverbrook", 4),
  },
  {
    ListingKey: "ubk-0016",
    ListingId: "X9504233",
    StandardStatus: "Active",
    UnparsedAddress: "440 Wilbrod Street",
    City: "Ottawa",
    StateOrProvince: "ON",
    PostalCode: "K1N 6M8",
    SubdivisionName: "Sandy Hill",
    Latitude: 45.4271,
    Longitude: -75.6764,
    ListPrice: 949000,
    PropertyType: "Residential",
    PropertySubType: "Duplex",
    BedroomsTotal: 5,
    BathroomsTotalInteger: 3,
    LivingArea: 2800,
    YearBuilt: 1912,
    PublicRemarks:
      "Income opportunity in Sandy Hill: legal duplex with a three-bedroom upper and two-bedroom lower, separate hydro meters, parking for three, and solid long-term tenants. Steps to uOttawa and the ByWard Market.",
    ListOfficeName: "Heritage River Realty, Brokerage",
    ModificationTimestamp: "2026-06-05T18:51:00Z",
    ListingContractDate: "2026-05-15",
    Media: media("sandyhill-duplex", 5),
  },
  {
    ListingKey: "ubk-0017",
    ListingId: "X9504399",
    StandardStatus: "Active",
    UnparsedAddress: "88 Stonehaven Drive",
    City: "Kanata",
    StateOrProvince: "ON",
    PostalCode: "K2M 2K2",
    SubdivisionName: "Bridlewood",
    Latitude: 45.2871,
    Longitude: -75.8842,
    ListPrice: 1049000,
    PropertyType: "Residential",
    PropertySubType: "Single Family Residence",
    BedroomsTotal: 5,
    BathroomsTotalInteger: 4,
    LivingArea: 3200,
    LotSizeArea: 0.16,
    YearBuilt: 2001,
    PublicRemarks:
      "Bridlewood five-bedroom with a rare main-floor in-law suite, renovated kitchen with double wall ovens, saltwater pool, and a heated garage. Walking distance to three schools and the Stonehaven trail network.",
    ListOfficeName: "Riverview Homes Realty, Brokerage",
    ModificationTimestamp: "2026-06-09T22:14:00Z",
    ListingContractDate: "2026-05-31",
    Media: media("kanata-bridlewood", 6),
  },
  {
    ListingKey: "ubk-0018",
    ListingId: "X9504512",
    StandardStatus: "Active",
    UnparsedAddress: "120 Marketplace Avenue Unit 612",
    City: "Ottawa",
    StateOrProvince: "ON",
    PostalCode: "K2J 5G3",
    SubdivisionName: "Barrhaven",
    Latitude: 45.2698,
    Longitude: -75.7459,
    ListPrice: 419900,
    PropertyType: "Residential",
    PropertySubType: "Condo Apartment",
    BedroomsTotal: 2,
    BathroomsTotalInteger: 1,
    LivingArea: 810,
    YearBuilt: 2020,
    PublicRemarks:
      "Stylish two-bedroom condo above Barrhaven Marketplace: quartz counters, in-suite laundry, a west-facing balcony, gym and party room in the building, plus one underground parking spot.",
    ListOfficeName: "Southbridge Realty Inc., Brokerage",
    ModificationTimestamp: "2026-06-10T16:05:00Z",
    ListingContractDate: "2026-06-08",
    Media: media("barrhaven-condo", 4),
  },
];
